language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t daticalamy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daticalamy/docker-react npm run test -- --coverage


